from collections.abc import Sequence


def setQuESTSeeds(arg: Sequence[int], /) -> None: ...

def getQuESTSeeds() -> list[int]: ...

def setQuESTSeedsToDefault() -> None: ...

def setQuESTValidationOn() -> None: ...

def setQuESTValidationOff() -> None: ...

def setQuESTValidationEpsilonToDefault() -> None: ...

def setQuESTValidationEpsilon(arg: float, /) -> None: ...

def getQuESTValidationEpsilon() -> float: ...

def setQuESTMaxNumReportedItems(arg0: int, arg1: int, /) -> None: ...

def setQuESTMaxNumReportedSigFigs(arg: int, /) -> None: ...

def setQuESTNumReportedNewlines(arg: int, /) -> None: ...

def setQuESTReportedPauliChars(arg: str, /) -> None: ...

def setQuESTReportedPauliStrStyle(arg: int, /) -> None: ...

def getQuESTGpuCacheSize() -> int: ...

def clearQuESTGpuCache() -> None: ...

def getQuESTEnvironmentString() -> str: ...
