from collections.abc import Sequence
from typing import overload


class QuESTEnv:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, /) -> None: ...

    @staticmethod
    def report() -> None: ...

    def __enter__(self) -> QuESTEnv: ...

    def __exit__(self, *args) -> bool: ...

    def syncQuESTEnv() -> None: ...

    def isQuESTEnvInit() -> int: ...

class PauliStr:
    @overload
    def __init__(self, arg0: str, arg1: Sequence[int], /) -> None: ...

    @overload
    def __init__(self, arg: str, /) -> None: ...

    def report(self) -> None: ...

class PauliStrSum:
    @overload
    def __init__(self, arg0: Sequence[PauliStr], arg1: Sequence[complex], /) -> None: ...

    @overload
    def __init__(self, arg: str, /) -> None: ...

    def __del__(self) -> None: ...

    def fromFile(self) -> PauliStrSum: ...

    def fromReversedFile(self) -> PauliStrSum: ...

    def report(self) -> None: ...

class Qureg:
    def __init__(self, arg: int, /) -> None: ...

    def __del__(self) -> None: ...

    def createDensityQureg(self) -> Qureg: ...

    def createForcedQureg(self) -> Qureg: ...

    def createForcedDensityQureg(self) -> Qureg: ...

    def createCustomQureg(self, arg0: int, arg1: int, arg2: int, arg3: int, /) -> Qureg: ...

    def createCloneQureg(self) -> Qureg: ...

    @overload
    def initBlankState(self) -> None: ...

    @overload
    def initBlankState(self) -> None: ...

    def initZeroState(self) -> None: ...

    def initPlusState(self) -> None: ...

    def initPureState(self, arg: Qureg, /) -> None: ...

    def initClassicalState(self, arg: int, /) -> None: ...

    def initDebugState(self) -> None: ...

    def initArbitraryPureState(self, arg: complex, /) -> None: ...

    def initRandomPureState(self) -> None: ...

    def initRandomMixedState(self, arg: int, /) -> None: ...

    def setQuregAmps(self, arg0: int, arg1: Sequence[complex], /) -> None: ...

    def setDensityQuregAmps(self, arg0: int, arg1: int, arg2: Sequence[Sequence[complex]], /) -> None: ...

    def setDensityQuregFlatAmps(self, arg0: int, arg1: Sequence[complex], /) -> None: ...

    def setQuregToClone(self, arg: Qureg, /) -> None: ...

    def setQuregToWeightedSum(self, arg0: Sequence[complex], arg1: Sequence[Qureg], /) -> None: ...

    def setQuregToMixture(self, arg0: Sequence[float], arg1: Sequence[Qureg], /) -> None: ...

    def setQuregToRenormalized(self) -> float: ...

    def setQuregToPauliStrSum(self, arg: PauliStrSum, /) -> None: ...

    def setQuregToPartialTrace(self, arg0: Qureg, arg1: Sequence[int], /) -> None: ...

    def setQuregToReducedDensityMatrix(self, arg0: Qureg, arg1: Sequence[int], /) -> None: ...

    def getQuregAmps(self, arg0: int, arg1: int, /) -> list[complex]: ...

    def getDensityQuregAmps(self, arg0: int, arg1: int, arg2: int, arg3: int, /) -> list[list[complex]]: ...

    def getQuregAmp(self, arg: int, /) -> complex: ...

    def getDensityQuregAmp(self, arg0: int, arg1: int, /) -> complex: ...

    def calcExpecPauliStr(self, arg: PauliStr, /) -> float: ...

    def calcExpecPauliStrSum(self, arg: PauliStrSum, /) -> float: ...

    def calcExpecFullStateDiagMatr(self, arg: FullStateDiagMatr, /) -> float: ...

    def calcExpecFullStateDiagMatrPower(self, arg0: FullStateDiagMatr, arg1: float, /) -> float: ...

    def calcProbOfBasisState(self, arg: int, /) -> float: ...

    def calcProbOfQubitOutcome(self, arg0: int, arg1: int, /) -> float: ...

    def calcProbOfMultiQubitOutcome(self, arg0: Sequence[int], arg1: Sequence[int], /) -> float: ...

    def calcProbsOfAllMultiQubitOutcomes(self, arg: Sequence[int], /) -> list[float]: ...

    def calcTotalProb(self) -> float: ...

    def calcPurity(self) -> float: ...

    def calcFidelity(self, arg: Qureg, /) -> float: ...

    def calcDistance(self, arg: Qureg, /) -> float: ...

    def calcPartialTrace(self, arg: Sequence[int], /) -> Qureg: ...

    def calcReducedDensityMatrix(self, arg: Sequence[int], /) -> Qureg: ...

    def calcInnerProduct(self, arg: Qureg, /) -> complex: ...

    def calcExpecNonHermitianPauliStrSum(self, arg: PauliStrSum, /) -> complex: ...

    def calcExpecNonHermitianFullStateDiagMatr(self, arg: FullStateDiagMatr, /) -> complex: ...

    def calcExpecNonHermitianFullStateDiagMatrPower(self, arg0: FullStateDiagMatr, arg1: complex, /) -> complex: ...

    def leftapplyCompMatr1(self, arg0: int, arg1: CompMatr1, /) -> None: ...

    def rightapplyCompMatr1(self, arg0: int, arg1: CompMatr1, /) -> None: ...

    def leftapplyCompMatr2(self, arg0: int, arg1: int, arg2: CompMatr2, /) -> None: ...

    def rightapplyCompMatr2(self, arg0: int, arg1: int, arg2: CompMatr2, /) -> None: ...

    def leftapplyCompMatr(self, arg0: Sequence[int], arg1: CompMatr, /) -> None: ...

    def rightapplyCompMatr(self, arg0: Sequence[int], arg1: CompMatr, /) -> None: ...

    def leftapplyDiagMatr1(self, arg0: int, arg1: DiagMatr1, /) -> None: ...

    def rightapplyDiagMatr1(self, arg0: int, arg1: DiagMatr1, /) -> None: ...

    def leftapplyDiagMatr2(self, arg0: int, arg1: int, arg2: DiagMatr2, /) -> None: ...

    def rightapplyDiagMatr2(self, arg0: int, arg1: int, arg2: DiagMatr2, /) -> None: ...

    def leftapplyDiagMatr(self, arg0: Sequence[int], arg1: DiagMatr, /) -> None: ...

    def rightapplyDiagMatr(self, arg0: Sequence[int], arg1: DiagMatr, /) -> None: ...

    def leftapplyDiagMatrPower(self, arg0: Sequence[int], arg1: DiagMatr, arg2: complex, /) -> None: ...

    def rightapplyDiagMatrPower(self, arg0: Sequence[int], arg1: DiagMatr, arg2: complex, /) -> None: ...

    def leftapplyFullStateDiagMatr(self, arg: FullStateDiagMatr, /) -> None: ...

    def rightapplyFullStateDiagMatr(self, arg: FullStateDiagMatr, /) -> None: ...

    def leftapplyFullStateDiagMatrPower(self, arg0: FullStateDiagMatr, arg1: complex, /) -> None: ...

    def rightapplyFullStateDiagMatrPower(self, arg0: FullStateDiagMatr, arg1: complex, /) -> None: ...

    def leftapplySwap(self, arg0: int, arg1: int, /) -> None: ...

    def rightapplySwap(self, arg0: int, arg1: int, /) -> None: ...

    def leftapplyPauliX(self, arg: int, /) -> None: ...

    def rightapplyPauliX(self, arg: int, /) -> None: ...

    def leftapplyPauliY(self, arg: int, /) -> None: ...

    def rightapplyPauliY(self, arg: int, /) -> None: ...

    def leftapplyPauliZ(self, arg: int, /) -> None: ...

    def rightapplyPauliZ(self, arg: int, /) -> None: ...

    def leftapplyPauliStr(self, arg: PauliStr, /) -> None: ...

    def rightapplyPauliStr(self, arg: PauliStr, /) -> None: ...

    def leftapplyPauliStrSum(self, arg0: PauliStrSum, arg1: Qureg, /) -> None: ...

    def rightapplyPauliStrSum(self, arg0: PauliStrSum, arg1: Qureg, /) -> None: ...

    def leftapplyPauliGadget(self, arg0: PauliStr, arg1: float, /) -> None: ...

    def rightapplyPauliGadget(self, arg0: PauliStr, arg1: float, /) -> None: ...

    def leftapplyPhaseGadget(self, arg0: Sequence[int], arg1: float, /) -> None: ...

    def rightapplyPhaseGadget(self, arg0: Sequence[int], arg1: float, /) -> None: ...

    def leftapplyMultiQubitNot(self, arg: Sequence[int], /) -> None: ...

    def rightapplyMultiQubitNot(self, arg: Sequence[int], /) -> None: ...

    def leftapplyQubitProjector(self, arg0: int, arg1: int, /) -> None: ...

    def rightapplyQubitProjector(self, arg0: int, arg1: int, /) -> None: ...

    def applyCompMatr1(self, arg0: int, arg1: CompMatr1, /) -> None: ...

    def applyControlledCompMatr1(self, arg0: int, arg1: int, arg2: CompMatr1, /) -> None: ...

    def applyMultiControlledCompMatr1(self, arg0: Sequence[int], arg1: int, arg2: CompMatr1, /) -> None: ...

    def applyMultiStateControlledCompMatr1(self, arg0: Sequence[int], arg1: Sequence[int], arg2: int, arg3: CompMatr1, /) -> None: ...

    def applyCompMatr2(self, arg0: int, arg1: int, arg2: CompMatr2, /) -> None: ...

    def applyControlledCompMatr2(self, arg0: int, arg1: int, arg2: int, arg3: CompMatr2, /) -> None: ...

    def applyMultiControlledCompMatr2(self, arg0: Sequence[int], arg1: int, arg2: int, arg3: CompMatr2, /) -> None: ...

    def applyMultiStateControlledCompMatr2(self, arg0: Sequence[int], arg1: Sequence[int], arg2: int, arg3: int, arg4: int, arg5: CompMatr2, /) -> None: ...

    def applyCompMatr(self, arg0: Sequence[int], arg1: CompMatr, /) -> None: ...

    def applyControlledCompMatr(self, arg0: int, arg1: Sequence[int], arg2: CompMatr, /) -> None: ...

    def applyMultiControlledCompMatr(self, arg0: Sequence[int], arg1: Sequence[int], arg2: CompMatr, /) -> None: ...

    def applyMultiStateControlledCompMatr(self, arg0: Sequence[int], arg1: Sequence[int], arg2: Sequence[int], arg3: CompMatr, /) -> None: ...

    def applyDiagMatr1(self, arg0: int, arg1: DiagMatr1, /) -> None: ...

    def applyControlledDiagMatr1(self, arg0: int, arg1: int, arg2: DiagMatr1, /) -> None: ...

    def applyMultiControlledDiagMatr1(self, arg0: Sequence[int], arg1: int, arg2: DiagMatr1, /) -> None: ...

    def applyMultiStateControlledDiagMatr1(self, arg0: Sequence[int], arg1: Sequence[int], arg2: int, arg3: DiagMatr1, /) -> None: ...

    def applyDiagMatr2(self, arg0: int, arg1: int, arg2: DiagMatr2, /) -> None: ...

    def applyControlledDiagMatr2(self, arg0: int, arg1: int, arg2: int, arg3: DiagMatr2, /) -> None: ...

    def applyMultiControlledDiagMatr2(self, arg0: Sequence[int], arg1: int, arg2: int, arg3: DiagMatr2, /) -> None: ...

    def applyMultiStateControlledDiagMatr2(self, arg0: Sequence[int], arg1: Sequence[int], arg2: int, arg3: int, arg4: DiagMatr2, /) -> None: ...

    def applyDiagMatr(self, arg0: Sequence[int], arg1: DiagMatr, /) -> None: ...

    def applyControlledDiagMatr(self, arg0: int, arg1: Sequence[int], arg2: DiagMatr, /) -> None: ...

    def applyMultiControlledDiagMatr(self, arg0: Sequence[int], arg1: Sequence[int], arg2: DiagMatr, /) -> None: ...

    def applyMultiStateControlledDiagMatr(self, arg0: Sequence[int], arg1: Sequence[int], arg2: Sequence[int], arg3: DiagMatr, /) -> None: ...

    def applyDiagMatrPower(self, arg0: Sequence[int], arg1: DiagMatr, arg2: complex, /) -> None: ...

    def applyControlledDiagMatrPower(self, arg0: int, arg1: Sequence[int], arg2: DiagMatr, arg3: complex, /) -> None: ...

    def applyMultiControlledDiagMatrPower(self, arg0: Sequence[int], arg1: Sequence[int], arg2: DiagMatr, arg3: complex, /) -> None: ...

    def applyMultiStateControlledDiagMatrPower(self, arg0: Sequence[int], arg1: Sequence[int], arg2: Sequence[int], arg3: DiagMatr, arg4: complex, /) -> None: ...

    def applyFullStateDiagMatr(self, arg: FullStateDiagMatr, /) -> None: ...

    def applyFullStateDiagMatrPower(self, arg0: FullStateDiagMatr, arg1: complex, /) -> None: ...

    def applyS(self, arg: int, /) -> None: ...

    def applyControlledS(self, arg0: int, arg1: int, /) -> None: ...

    def applyMultiControlledS(self, arg0: Sequence[int], arg1: int, /) -> None: ...

    def applyT(self, arg: int, /) -> None: ...

    def applyControlledT(self, arg0: int, arg1: int, /) -> None: ...

    def applyMultiControlledT(self, arg0: Sequence[int], arg1: int, /) -> None: ...

    def applyMultiStateControlledT(self, arg0: Sequence[int], arg1: Sequence[int], arg2: int, /) -> None: ...

    def applyHadamard(self, arg: int, /) -> None: ...

    def applyControlledHadamard(self, arg0: int, arg1: int, /) -> None: ...

    def applyMultiControlledHadamard(self, arg0: Sequence[int], arg1: int, /) -> None: ...

    def applyMultiStateControlledHadamard(self, arg0: Sequence[int], arg1: Sequence[int], arg2: int, /) -> None: ...

    def applySwap(self, arg0: int, arg1: int, /) -> None: ...

    def applyControlledSwap(self, arg0: int, arg1: int, arg2: int, /) -> None: ...

    def applyMultiControlledSwap(self, arg0: Sequence[int], arg1: int, arg2: int, /) -> None: ...

    def applyMultiStateControlledSwap(self, arg0: Sequence[int], arg1: Sequence[int], arg2: int, arg3: int, /) -> None: ...

    def applySqrtSwap(self, arg0: int, arg1: int, /) -> None: ...

    def applyControlledSqrtSwap(self, arg0: int, arg1: int, arg2: int, /) -> None: ...

    def applyMultiControlledSqrtSwap(self, arg0: Sequence[int], arg1: int, arg2: int, /) -> None: ...

    def applyPauliX(self, arg: int, /) -> None: ...

    def applyPauliY(self, arg: int, /) -> None: ...

    def applyPauliZ(self, arg: int, /) -> None: ...

    def applyControlledPauliX(self, arg0: int, arg1: int, /) -> None: ...

    def applyControlledPauliY(self, arg0: int, arg1: int, /) -> None: ...

    def applyControlledPauliZ(self, arg0: int, arg1: int, /) -> None: ...

    def applyMultiControlledPauliX(self, arg0: Sequence[int], arg1: int, /) -> None: ...

    def applyMultiControlledPauliY(self, arg0: Sequence[int], arg1: int, /) -> None: ...

    def applyMultiControlledPauliZ(self, arg0: Sequence[int], arg1: int, /) -> None: ...

    def applyMultiStateControlledPauliX(self, arg0: Sequence[int], arg1: Sequence[int], arg2: int, /) -> None: ...

    def applyMultiStateControlledPauliY(self, arg0: Sequence[int], arg1: Sequence[int], arg2: int, /) -> None: ...

    def applyMultiStateControlledPauliZ(self, arg0: Sequence[int], arg1: Sequence[int], arg2: int, /) -> None: ...

    def applyPauliStr(self, arg: PauliStr, /) -> None: ...

    def applyControlledPauliStr(self, arg0: int, arg1: PauliStr, /) -> None: ...

    def applyMultiControlledPauliStr(self, arg0: Sequence[int], arg1: PauliStr, /) -> None: ...

    def applyMultiStateControlledPauliStr(self, arg0: Sequence[int], arg1: Sequence[int], arg2: PauliStr, /) -> None: ...

    def applyRotateX(self, arg0: int, arg1: float, /) -> None: ...

    def applyRotateY(self, arg0: int, arg1: float, /) -> None: ...

    def applyRotateZ(self, arg0: int, arg1: float, /) -> None: ...

    def applyControlledRotateX(self, arg0: int, arg1: int, arg2: float, /) -> None: ...

    def applyControlledRotateY(self, arg0: int, arg1: int, arg2: float, /) -> None: ...

    def applyControlledRotateZ(self, arg0: int, arg1: int, arg2: float, /) -> None: ...

    def applyMultiControlledRotateX(self, arg0: Sequence[int], arg1: int, arg2: float, /) -> None: ...

    def applyMultiControlledRotateY(self, arg0: Sequence[int], arg1: int, arg2: float, /) -> None: ...

    def applyMultiControlledRotateZ(self, arg0: Sequence[int], arg1: int, arg2: float, /) -> None: ...

    def applyMultiStateControlledRotateX(self, arg0: Sequence[int], arg1: Sequence[int], arg2: int, arg3: float, /) -> None: ...

    def applyMultiStateControlledRotateY(self, arg0: Sequence[int], arg1: Sequence[int], arg2: int, arg3: float, /) -> None: ...

    def applyMultiStateControlledRotateZ(self, arg0: Sequence[int], arg1: Sequence[int], arg2: int, arg3: float, /) -> None: ...

    def applyRotateAroundAxis(self, arg0: int, arg1: float, arg2: float, arg3: float, arg4: float, /) -> None: ...

    def applyControlledRotateAroundAxis(self, arg0: int, arg1: int, arg2: float, arg3: float, arg4: float, arg5: float, /) -> None: ...

    def applyMultiControlledRotateAroundAxis(self, arg0: Sequence[int], arg1: int, arg2: float, arg3: float, arg4: float, arg5: float, /) -> None: ...

    def applyMultiStateControlledRotateAroundAxis(self, arg0: Sequence[int], arg1: Sequence[int], arg2: int, arg3: float, arg4: float, arg5: float, arg6: float, /) -> None: ...

    def applyPauliGadget(self, arg0: PauliStr, arg1: float, /) -> None: ...

    def applyNonUnitaryPauliGadget(self, arg0: PauliStr, arg1: complex, /) -> None: ...

    def applyControlledPauliGadget(self, arg0: int, arg1: PauliStr, arg2: float, /) -> None: ...

    def applyMultiControlledPauliGadget(self, arg0: Sequence[int], arg1: PauliStr, arg2: float, /) -> None: ...

    def applyMultiStateControlledPauliGadget(self, arg0: Sequence[int], arg1: Sequence[int], arg2: PauliStr, arg3: float, /) -> None: ...

    def applyPhaseGadget(self, arg0: Sequence[int], arg1: float, /) -> None: ...

    def applyControlledPhaseGadget(self, arg0: int, arg1: Sequence[int], arg2: float, /) -> None: ...

    def applyMultiControlledPhaseGadget(self, arg0: Sequence[int], arg1: Sequence[int], arg2: float, /) -> None: ...

    def applyMultiStateControlledPhaseGadget(self, arg0: Sequence[int], arg1: Sequence[int], arg2: Sequence[int], arg3: float, /) -> None: ...

    def applyPhaseFlip(self, arg: int, /) -> None: ...

    def applyPhaseShift(self, arg0: int, arg1: float, /) -> None: ...

    def applyTwoQubitPhaseFlip(self, arg0: int, arg1: int, /) -> None: ...

    def applyTwoQubitPhaseShift(self, arg0: int, arg1: int, arg2: float, /) -> None: ...

    def applyMultiQubitPhaseFlip(self, arg: Sequence[int], /) -> None: ...

    def applyMultiQubitPhaseShift(self, arg0: Sequence[int], arg1: float, /) -> None: ...

    def applyMultiQubitNot(self, arg: Sequence[int], /) -> None: ...

    def applyControlledMultiQubitNot(self, arg0: int, arg1: Sequence[int], /) -> None: ...

    def applyMultiControlledMultiQubitNot(self, arg0: Sequence[int], arg1: Sequence[int], /) -> None: ...

    def applyMultiStateControlledMultiQubitNot(self, arg0: Sequence[int], arg1: Sequence[int], arg2: Sequence[int], /) -> None: ...

    def applyQubitMeasurement(self, arg: int, /) -> int: ...

    def applyForcedQubitMeasurement(self, arg0: int, arg1: int, /) -> float: ...

    def applyForcedMultiQubitMeasurement(self, arg0: Sequence[int], arg1: Sequence[int], /) -> float: ...

    def applyQubitProjector(self, arg0: int, arg1: int, /) -> None: ...

    def applyMultiQubitProjector(self, arg0: Sequence[int], arg1: Sequence[int], /) -> None: ...

    def applyQuantumFourierTransform(self, arg: Sequence[int], /) -> None: ...

    def applyFullQuantumFourierTransform(self) -> None: ...

    def mixDephasing(self, arg0: int, arg1: float, /) -> None: ...

    def mixTwoQubitDephasing(self, arg0: int, arg1: int, arg2: float, /) -> None: ...

    def mixDepolarising(self, arg0: int, arg1: float, /) -> None: ...

    def mixTwoQubitDepolarising(self, arg0: int, arg1: int, arg2: float, /) -> None: ...

    def mixDamping(self, arg0: int, arg1: float, /) -> None: ...

    def mixPaulis(self, arg0: int, arg1: float, arg2: float, arg3: float, /) -> None: ...

    def mixQureg(self, arg0: Qureg, arg1: float, /) -> None: ...

    def mixKrausMap(self, arg0: Sequence[int], arg1: KrausMap, /) -> None: ...

    def mixSuperOp(self, arg0: Sequence[int], arg1: SuperOp, /) -> None: ...

    def applyTrotterizedPauliStrSumGadget(self, arg0: PauliStrSum, arg1: float, arg2: int, arg3: int, /) -> None: ...

    def applyTrotterizedControlledPauliStrSumGadget(self, arg0: int, arg1: PauliStrSum, arg2: float, arg3: int, arg4: int, /) -> None: ...

    def applyTrotterizedMultiControlledPauliStrSumGadget(self, arg0: Sequence[int], arg1: PauliStrSum, arg2: float, arg3: int, arg4: int, /) -> None: ...

    def applyTrotterizedMultiStateControlledPauliStrSumGadget(self, arg0: Sequence[int], arg1: Sequence[int], arg2: PauliStrSum, arg3: float, arg4: int, arg5: int, /) -> None: ...

    def applyTrotterizedNonUnitaryPauliStrSumGadget(self, arg0: PauliStrSum, arg1: complex, arg2: int, arg3: int, /) -> None: ...

    def applyTrotterizedUnitaryTimeEvolution(self, arg0: PauliStrSum, arg1: float, arg2: int, arg3: int, /) -> None: ...

    def applyTrotterizedImaginaryTimeEvolution(self, arg0: PauliStrSum, arg1: float, arg2: int, arg3: int, /) -> None: ...

    def applyTrotterizedNoisyTimeEvolution(self, arg0: PauliStrSum, arg1: float, arg2: PauliStrSum, arg3: int, arg4: float, arg5: int, arg6: int, /) -> None: ...

    def syncQuregToGpu(self) -> None: ...

    def syncQuregFromGpu(self) -> None: ...

    def syncSubQuregToGpu(self, arg0: int, arg1: int, /) -> None: ...

    def syncSubQuregFromGpu(self, arg0: int, arg1: int, /) -> None: ...

    def reportQuregParams(self) -> None: ...

    def report(self) -> None: ...

class KrausMap:
    @overload
    def __init__(self, arg0: int, arg1: int, /) -> None: ...

    @overload
    def __init__(self, arg0: int, arg1: int, arg2: Sequence[Sequence[Sequence[complex]]], /) -> None: ...

    def set(self, arg: Sequence[Sequence[Sequence[complex]]], /) -> None: ...

    def __del__(self) -> None: ...

    def sync(self) -> None: ...

    def report(self) -> None: ...

class SuperOp:
    @overload
    def __init__(self, arg: int, /) -> None: ...

    @overload
    def __init__(self, arg0: int, arg1: Sequence[Sequence[complex]], /) -> None: ...

    def set(self, arg: Sequence[Sequence[complex]], /) -> None: ...

    def __del__(self) -> None: ...

    def sync(self) -> None: ...

    def report(self) -> None: ...

class CompMatr1:
    def __init__(self, arg: Sequence[Sequence[complex]], /) -> None: ...

    def report(self) -> None: ...

class CompMatr2:
    def __init__(self, arg: Sequence[Sequence[complex]], /) -> None: ...

    def report(self) -> None: ...

class CompMatr:
    def __init__(self, arg: int, /) -> None: ...

    def set(self, arg: Sequence[Sequence[complex]], /) -> None: ...

    def __del__(self) -> None: ...

    def sync(self) -> None: ...

    def report(self) -> None: ...

class DiagMatr1:
    def __init__(self, arg: Sequence[complex], /) -> None: ...

    def report(self) -> None: ...

class DiagMatr2:
    def __init__(self, arg: Sequence[complex], /) -> None: ...

    def report(self) -> None: ...

class DiagMatr:
    def __init__(self, arg: int, /) -> None: ...

    def set(self, arg: Sequence[complex], /) -> None: ...

    def __del__(self) -> None: ...

    def sync(self) -> None: ...

    def report(self) -> None: ...

class FullStateDiagMatr:
    def __init__(self, arg: int, /) -> None: ...

    def set(self, arg0: int, arg1: Sequence[complex], /) -> None: ...

    def __del__(self) -> None: ...

    def sync(self) -> None: ...

    def report(self) -> None: ...
