from collections.abc import Sequence

import quiche.bindings.quest_bindings


def getHartreeFockStateJW(num_electrons: int) -> int: ...

def getHartreeFockStateBK(num_electrons: int, num_qubits: int) -> int: ...

def getHartreeFockStateParity(num_electrons: int, num_qubits: int) -> int: ...

def getPhaseTextbookTrotter(qureg: quiche.bindings.quest_bindings.Qureg, hamiltonian: quiche.bindings.quest_bindings.PauliStrSum, ancillas: Sequence[int], order: int, reps: int, time: float) -> float: ...

def getPhaseKitaevTrotter(qureg: quiche.bindings.quest_bindings.Qureg, hamiltonian: quiche.bindings.quest_bindings.PauliStrSum, ancilla_index: int, order: int, reps: int, time: float, num_bits: int) -> float: ...

def getPhaseTextbookQDRIFT(qureg: quiche.bindings.quest_bindings.Qureg, hamiltonian: quiche.bindings.quest_bindings.PauliStrSum, ancillas: Sequence[int], reps: int, time: float, seed: int | None = None) -> float: ...

def getPhaseKitaevQDRIFT(qureg: quiche.bindings.quest_bindings.Qureg, hamiltonian: quiche.bindings.quest_bindings.PauliStrSum, ancilla_index: int, reps: int, time: float, num_bits: int, seed: int | None = None) -> float: ...

def getPhaseTextbookQubitised(qureg: quiche.bindings.quest_bindings.Qureg, hamiltonian: quiche.bindings.quest_bindings.PauliStrSum, qpe_ancillas: Sequence[int], qubitisation_ancillas: Sequence[int]) -> float: ...

def getPhaseNaiveTrotter(qureg: quiche.bindings.quest_bindings.Qureg, hamiltonian: quiche.bindings.quest_bindings.PauliStrSum, ancilla_index: int, order: int, reps: int, time: float) -> float: ...

def getPhaseNaiveQDRIFT(qureg: quiche.bindings.quest_bindings.Qureg, hamiltonian: quiche.bindings.quest_bindings.PauliStrSum, ancilla_index: int, reps: int, time: float, seed: int | None = None) -> float: ...

def getPhaseIterativeTrotter(qureg: quiche.bindings.quest_bindings.Qureg, hamiltonian: quiche.bindings.quest_bindings.PauliStrSum, ancilla_index: int, order: int, reps: int, time: float, num_bits: int) -> float: ...

def getPhaseIterativeQDRIFT(qureg: quiche.bindings.quest_bindings.Qureg, hamiltonian: quiche.bindings.quest_bindings.PauliStrSum, ancilla_index: int, reps: int, time: float, num_bits: int, seed: int | None = None) -> float: ...

def getPhaseTextbookQubitisedOptimised(qureg: quiche.bindings.quest_bindings.Qureg, hamiltonian: quiche.bindings.quest_bindings.PauliStrSum, qpe_ancillas: Sequence[int], qubitisation_ancillas: Sequence[int]) -> float: ...

def initClassicalState(qureg: quiche.bindings.quest_bindings.Qureg, state: Sequence[int]) -> None: ...
